### ISSUE TITLE
Could not exit program after dying

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/ASCII-axe#4]
Hey Chris(@cyberfilth),

While trying Alpha 33 I could not exit the game after I died.

Cheers,
Gus

**Comment by cyberfilth** [comment]
Ah, the game over screen is still being worked on so the menu text isn't finished yet. 'x' should exit the game over screen though

**Comment by cyberfilth** [comment]
I've added a hint at the bottom of the Game Over screen now. More will be added later that allow you to view game stats.

**Comment by gcarreno** [comment]
Hey Chris(@cyberfilth),

Thanks for that, it work a charm.

Closing!!

Cheers,
Gus
