### ISSUE TITLE
Are all keys suposed to be caps?

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/ASCII-axe#5]
Hey Chris(@cyberfilth),

Are all keys supposed to be caps or is there a mixture?

In the menus provided it's not clear that they are Caps and on "Axes-Armour-Ale" I don't think any where caps...

It's a bit confusing, sorry!!

Cheers,
Gus

**Comment by cyberfilth** [comment]
Keys are usually case insensitive, the only exception is in menus where items have a lowercase letter designated to them and actions have uppercase letters.

**Comment by gcarreno** [comment]
Hey Chris(@cyberfilth),

On the GUI version you've opted for numbers.

Why the change of heart on this version?
Is it due to the limitation of only 10 items?

Cheers,
Gus

**Comment by cyberfilth** [comment]
Exactly that, different characters will have different carrying capacity... at some point, so will have more inventory slots available

**Comment by gcarreno** [comment]
Hey Chris(@cyberfilth),

Yeah, that makes absolute sense.

Well, as long as you can limit the caps diff only to the inventory menu, and somehow make that obvious or clear, I guess there isn't much I can fault on your logic.

Feel free to close this at your leisure. My curiosity is satisfied and once you explain it on the inventory menu, all will make sense for the user.

Cheers,
Gus

**Comment by cyberfilth** [comment]
Cool, closing for now
