### ISSUE TITLE
E[x]it to menu doesn't work

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/ASCII-axe#6]
Hey Chris(@cyberfilth),

In this image, that you access by double ESC on the game, the x or X doesn't do anything:
![Selection_001](https://user-images.githubusercontent.com/81799/133442967-9f302243-3a38-45d5-bb7a-756989cd5376.png)

I've tried small x and big X and nothing happens.

Cheers,
Gus

**Comment by cyberfilth** [comment]
This is one of those jobs that I'll "come back to at some point", thanks for the reminder. It's been overlooked for too long so I'll add it to the next bunch of fixes.

**Comment by gcarreno** [comment]
Hey Chris(@cyberfilth),

Not a prob mate, you take your time :)

You'll always have this nag here for future ref, eheheheh
I'm friendly like that :stuck_out_tongue: 

Cheers,
Gus

**Comment by cyberfilth** [comment]
This should now work in the latest update. Along with a warning message when starting a new game so that the old save isn't overwritten.
