### ISSUE TITLE
Forgot to change .gitignore on the binary name change

### ISSUE THREAD

**Issue by gcarreno** [cyberfilth/ASCII-axe#7]
Hey Chris(@cyberfilth),

Just like the subject mentions, you forgot to sync the `.gitignore` file to reflect the binary name change.

Cheers,
Gus

**Comment by cyberfilth** [comment]
Good catch! Thanks for that, it's been added now.

**Comment by gcarreno** [comment]
Hey Chris(@cyberfilth),

No probs mate, you're more than welcome!!

Cheers,
Gus
